# Generated by Django 5.1.1 on 2024-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_employee_user_student_user_warden_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_students',
            field=models.ManyToManyField(blank=True, related_name='current_roommates', to='hostel.student'),
        ),
    ]
