# Generated by Django 5.1.1 on 2024-09-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_room_current_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messdetails',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='messdetails',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='messdetails',
            name='week_start',
        ),
        migrations.AddField(
            model_name='messdetails',
            name='breakfast',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='messdetails',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
        ),
        migrations.AddField(
            model_name='messdetails',
            name='dinner',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='messdetails',
            name='lunch',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='messdetails',
            name='snacks',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
    ]
