# Generated by Django 5.1.1 on 2024-09-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_remove_messdetails_menu_remove_messdetails_week_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_students',
            field=models.ManyToManyField(blank=True, related_name='roommates', to='hostel.student'),
        ),
    ]
