# Generated by Django 5.1.1 on 2024-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_alter_room_current_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messdetails',
            name='breakfast',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='messdetails',
            name='dinner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='messdetails',
            name='lunch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='messdetails',
            name='snacks',
            field=models.CharField(default='', max_length=255),
        ),
    ]
